name: Test
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        nim-version: [devel, '2.0.0']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: nimble test -y --verbose
